### ISSUE TITLE
Cloudflare Argo - High CPU usage when using less than 3 tunnels

### ISSUE THREAD

**Issue by ilarrain** [wlatic/hassio.addons#11]
Thanks for the addon.
I'm using argo with 1 domain, and have always seen around 40%-50% cpu usage, regardless of load.
Today I've decided to investigate the issue. cloudflared cpu usage was less than 1%.
I've built the addon locally, updating cloudflared to the latest version, cpu usage was the same. Then I've removed 2nd and 3rd tunnel support, and CPU load is now less than 1%.

**Comment by wlatic** [comment]
Looking into this!

**Comment by wlatic** [comment]
Was poor coding. I never disabled the service when it wasnt needed so it just sat there starting and restarting the services. New version should come up now.
