### ISSUE TITLE
cf-ha.json written to wrong location

### ISSUE THREAD

**Issue by jwsample** [wlatic/hassio.addons#12]
While struggling to get this up and running again after the upgrade I ran into a bug that will probably stop any fresh installs from working.
It appears the service wants to find cf-ha.json in the cf-argo directory, but at startup writes it to the /config root instead.
I believe the cause is here:
```
if ! bashio::fs.file_exists "/config/cf-argo/cf-ha.json"; then
/opt/cloudflared --origincert=${certificate} --cred-file=/config/cf-ha.json tunnel create homeassistant
fi
```

After manually moving the created /config/cf-ha.json to /config/cf-argo/cf-ha.json its getting closer to working.

**Comment by wlatic** [comment]
Yep you are 100% right. Updated that now.

**Comment by jwsample** [comment]
Thanks!
