### ISSUE TITLE
Unable to scan QR code to link app account

### ISSUE THREAD

**Issue by tommy21osu** [wlatic/hassio.addons#5]
I'm having an issue linking my app account with tuya website. I can get to this point:
_"Next Click Cloud > Link Devices > Link Devices By App Account > Add App account (this will show a barcode on screen)
Within your smart life or Tuya app, click "Me" at the bottom right of the screen and then the icon on the top right (its a camera Icon), you can then scan the barcode."_
But it quickly displays the QR code has expired. Looks like others are having problems with same procedures on other tuya addons that require adding app to website.
Any ideas or alternatives besides android app hacks?

**Comment by wlatic** [comment]
Sorry for taking so long to get back.

One thing I'd check is your account profile on IOT tuya. I can imagine if you arent on the same timezone as your phone the QR code may not work.
