### ISSUE TITLE
[OpenALPR-Hassio ADDON] Integration in Home Assistant

### ISSUE THREAD

**Issue by thundergreen** [wlatic/hassio.addons#6]
I found this addon as it is not possible to run the OpenALPR on Supervised install. Therefre I installed this addon but I am now wondering how I could get this integrated into home assistant. I am running Frigate which will offer me snapshots once a car is detected. This pic I would like to use to identify via OpenALPR. How would that be possible to archieve?

Would be super happy to work this uut with you :)

**Comment by wlatic** [comment]
Sorry the details werent better.

After placing your picture here: /config/oalpr/data/plate.jpg

Say for example your Home Assistant IP address is 192.168.1.5 you’d run:

http://192.168.1.5:5000/plate

The above fires openalpr to analyse the picture and provides an output.

I was using this via nodered.

This was a very simple install of openalpr which I was going to use for something but ended up going a different way!

**Comment by thundergreen** [comment]
Sounds neat but it's not really clear how to get this really running. I mean I'd like to make an automation and i gueess it will work with shell commands then. but sorry being dumb i am wondering if it can create sensor or something or how would i fetch the information about the recognised plate then? 

If yoou went another way to get registration plate recognition.. would you mind sharing your setup?

**Comment by wlatic** [comment]
I ended up going with wyze cams.

Really you'd need to use something like NodeRed to be able to use the addon correctly. I just made an easy way of installing it.
