### ISSUE TITLE
Tuyagrab wont install

### ISSUE THREAD

**Issue by jmadden91** [wlatic/hassio.addons#7]
Hey mate, 

Looks like TuyaGrab won't install through supervisor in the latest version of home assistant.

21-03-09 12:29:50 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 367cd613/amd64-addon-tuyagrab:0.6: The command '/bin/bash -o pipefail -c apk add --no-cache         g++=9.3.0-r2         gcc=9.3.0-r2         libc-dev=0.7.2-r3         linux-headers=5.4.5-r1         make=4.3-r0         py3-pip=20.1.1-r0         python3-dev=3.8.5-r0 && apk add --no-cache         python3=3.8.5-r0 && apk add py3-cryptography py3-pip python3 && python3 -m pip install tinytuya' returned a non-zero code: 1
21-03-09 12:29:50 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
[WARNING]: Empty continuation line found in:
    RUN apk add --no-cache         g++=9.3.0-r2         gcc=9.3.0-r2         libc-dev=0.7.2-r3         linux-headers=5.4.5-r1         make=4.3-r0         py3-pip=20.1.1-r0         python3-dev=3.8.5-r0 && apk add --no-cache         python3=3.8.5-r0 && apk add py3-cryptography py3-pip python3 && python3 -m pip install tinytuya
[WARNING]: Empty continuation lines will become errors in a future release.

__________________________________________________________________________________________

Step 1/17 : ARG BUILD_FROM=hassioaddons/base:8.0.6
Step 2/17 : FROM ${BUILD_FROM}
 ---> 13cf499200eb
Step 3/17 : WORKDIR /opt
 ---> Using cache
 ---> 8890d5167f5e
Step 4/17 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 4914c14ff48e
Step 5/17 : RUN apk add --no-cache         g++=9.3.0-r2         gcc=9.3.0-r2         libc-dev=0.7.2-r3         linux-headers=5.4.5-r1         make=4.3-r0         py3-pip=20.1.1-r0         python3-dev=3.8.5-r0 && apk add --no-cache         python3=3.8.5-r0 && apk add py3-cryptography py3-pip python3 && python3 -m pip install tinytuya
 ---> Running in 04a6307d6e9f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:

  python3-dev-3.8.5-r1:
    breaks: world[python3-dev=3.8.5-r0]
Removing intermediate container 04a6307d6e9f

**Comment by wlatic** [comment]
Thank you for the report.

For some reason I put versioning of items in the first iteration. Taken those out now and it should install without issues.

**Comment by jmadden91** [comment]
Perfect, that has fixed it. Thanks for the quick turn around and all your work on the project.
