### ISSUE TITLE
Tuya Grab on Hassio/Py

### ISSUE THREAD

**Issue by wmillea** [wlatic/hassio.addons#9]
I thought I'd give this a try.  Didn't go quite as planned.

From the log. . . 

Add-on version: 0.7 You are running the latest version of this add-on. parse error: Expected string key before ':' at line 1, column 4 [18:41:44] ERROR: Unknown HTTP error occured System: (aarch64 / raspberrypi4-64) Home Assistant Core: 2021.4.4 Home Assistant Supervisor: 2021.04.0 ------------------------

Bill

**Comment by wlatic** [comment]
@wmillea have you filled out the configuration of the application?

The config being incorrect or not filled out is the main reason this happens.

**Comment by wmillea** [comment]
Thanks.  I'll take another look at it later.

Bill
